"""empty message

Revision ID: e65cfb8ff8b8
Revises: 
Create Date: 2022-05-15 12:12:57.374624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65cfb8ff8b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment',
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('parcel_quantity', sa.Integer(), nullable=True),
    sa.Column('weight_', sa.Float(), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_table('parcel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('parcel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcel')
    op.drop_table('warehouse')
    op.drop_table('shipment')
    op.drop_table('category')
    # ### end Alembic commands ###
